version: '3.8'

services:
  app:
    image: python:3.12.2-alpine3.19
    ports:
      - "5001:5000"
    volumes:
      - .:/app
      - static_volume:/app/static
    working_dir: /app
    entrypoint: ["/bin/sh", "-c"]
    command: |
      set -e &&
      apk add --no-cache bash postgresql-libs && 
      apk add --no-cache --virtual .build-deps gcc musl-dev postgresql-dev &&
      pip install -r requirements.txt &&
      export FLASK_APP=main.py &&
      flask run --host=0.0.0.0 --port=5000
    depends_on:
      - db
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql://warrior:12345@db:5432/sensor_db
      - FLASK_ENV=development

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: warrior
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: sensor_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  static_volume:

