version: '3.8'

volumes:
  static_volume:

services:
  app:
    restart: always
    image: 471112761484.dkr.ecr.eu-central-1.amazonaws.com/warrior:latest
    ports:
      - "80:5000"
    volumes:
      - .:/app
      - static_volume:/app/static
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql://warrior:pass@postgres-db1.ctyge4wgoiux.eu-central-1.rds.amazonaws.com:5432/postgresdb
      - FLASK_ENV=development
